*** Starting uWSGI 2.0.15 (64bit) on [Sun Apr 23 18:18:31 2017] ***
compiled with version: 5.4.0 20160609 on 23 April 2017 16:50:33
os: Linux-4.4.0-1013-aws #22-Ubuntu SMP Fri Mar 31 15:41:31 UTC 2017
nodename: ip-172-31-10-214
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ubuntu/gericare
detected binary path: /home/ubuntu/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ubuntu/gericare
your processes number limit is 3902
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...552 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x199b0e0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 800448 bytes (781 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x199b0e0 pid: 1467 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1467)
spawned uWSGI worker 1 (pid: 1470, cores: 1)
spawned uWSGI worker 2 (pid: 1471, cores: 1)
spawned uWSGI worker 3 (pid: 1472, cores: 1)
spawned uWSGI worker 4 (pid: 1473, cores: 1)
spawned uWSGI worker 5 (pid: 1474, cores: 1)
spawned uWSGI worker 6 (pid: 1475, cores: 1)
spawned uWSGI worker 7 (pid: 1476, cores: 1)
spawned uWSGI worker 8 (pid: 1477, cores: 1)
spawned uWSGI worker 9 (pid: 1478, cores: 1)
spawned uWSGI worker 10 (pid: 1479, cores: 1)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
worker 6 buried after 1 seconds
worker 7 buried after 1 seconds
worker 8 buried after 1 seconds
worker 9 buried after 1 seconds
worker 10 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/ubuntu/gericare
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (:8001)
running /home/ubuntu/.local/bin/uwsgi
[uWSGI] getting INI configuration from gericaresite_uwsgi.ini
[uwsgi-static] added check for /home/ubuntu/gericare/static/
*** Starting uWSGI 2.0.15 (64bit) on [Sun Apr 23 18:19:11 2017] ***
compiled with version: 5.4.0 20160609 on 23 April 2017 16:50:33
os: Linux-4.4.0-1013-aws #22-Ubuntu SMP Fri Mar 31 15:41:31 UTC 2017
nodename: ip-172-31-10-214
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ubuntu/gericare
detected binary path: /home/ubuntu/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ubuntu/gericare
your processes number limit is 3902
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...552 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address :8001 fd 3
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xdaa090
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 800448 bytes (781 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xdaa090 pid: 1467 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1467)
spawned uWSGI worker 1 (pid: 1488, cores: 1)
spawned uWSGI worker 2 (pid: 1489, cores: 1)
spawned uWSGI worker 3 (pid: 1490, cores: 1)
spawned uWSGI worker 4 (pid: 1491, cores: 1)
spawned uWSGI worker 5 (pid: 1492, cores: 1)
spawned uWSGI worker 6 (pid: 1493, cores: 1)
spawned uWSGI worker 7 (pid: 1494, cores: 1)
spawned uWSGI worker 8 (pid: 1495, cores: 1)
spawned uWSGI worker 9 (pid: 1496, cores: 1)
spawned uWSGI worker 10 (pid: 1497, cores: 1)
Sun Apr 23 18:20:01 2017 - uWSGI worker 9 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Sun Apr 23 18:20:01 2017 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.15 (64bit) on [Sun Apr 23 18:20:23 2017] ***
compiled with version: 5.4.0 20160609 on 23 April 2017 16:50:33
os: Linux-4.4.0-1013-aws #22-Ubuntu SMP Fri Mar 31 15:41:31 UTC 2017
nodename: ip-172-31-10-214
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ubuntu/gericare
detected binary path: /home/ubuntu/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ubuntu/gericare
your processes number limit is 3902
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...552 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xca50e0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 800448 bytes (781 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xca50e0 pid: 1513 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1513)
spawned uWSGI worker 1 (pid: 1516, cores: 1)
spawned uWSGI worker 2 (pid: 1517, cores: 1)
spawned uWSGI worker 3 (pid: 1518, cores: 1)
spawned uWSGI worker 4 (pid: 1519, cores: 1)
spawned uWSGI worker 5 (pid: 1520, cores: 1)
spawned uWSGI worker 6 (pid: 1521, cores: 1)
spawned uWSGI worker 7 (pid: 1522, cores: 1)
spawned uWSGI worker 8 (pid: 1523, cores: 1)
spawned uWSGI worker 9 (pid: 1524, cores: 1)
spawned uWSGI worker 10 (pid: 1525, cores: 1)
...brutally killing workers...
Gracefully killing worker 1 (pid: 1516)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
worker 6 buried after 1 seconds
worker 7 buried after 1 seconds
worker 8 buried after 1 seconds
worker 9 buried after 1 seconds
worker 10 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/ubuntu/gericare
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (:8001)
running /home/ubuntu/.local/bin/uwsgi
[uWSGI] getting INI configuration from gericaresite_uwsgi.ini
[uwsgi-static] added check for /home/ubuntu/gericare/static/
*** Starting uWSGI 2.0.15 (64bit) on [Sun Apr 23 18:20:36 2017] ***
compiled with version: 5.4.0 20160609 on 23 April 2017 16:50:33
os: Linux-4.4.0-1013-aws #22-Ubuntu SMP Fri Mar 31 15:41:31 UTC 2017
nodename: ip-172-31-10-214
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ubuntu/gericare
detected binary path: /home/ubuntu/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ubuntu/gericare
your processes number limit is 3902
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...552 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address :8001 fd 3
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x2056090
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 800448 bytes (781 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x2056090 pid: 1513 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1513)
spawned uWSGI worker 1 (pid: 1619, cores: 1)
spawned uWSGI worker 2 (pid: 1620, cores: 1)
spawned uWSGI worker 3 (pid: 1621, cores: 1)
spawned uWSGI worker 4 (pid: 1622, cores: 1)
spawned uWSGI worker 5 (pid: 1623, cores: 1)
spawned uWSGI worker 6 (pid: 1624, cores: 1)
spawned uWSGI worker 7 (pid: 1625, cores: 1)
spawned uWSGI worker 8 (pid: 1626, cores: 1)
spawned uWSGI worker 9 (pid: 1627, cores: 1)
spawned uWSGI worker 10 (pid: 1628, cores: 1)
Sun Apr 23 18:22:05 2017 - uWSGI worker 6 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.15 (64bit) on [Sun Apr 23 18:25:10 2017] ***
compiled with version: 5.4.0 20160609 on 23 April 2017 16:50:33
os: Linux-4.4.0-1013-aws #22-Ubuntu SMP Fri Mar 31 15:41:31 UTC 2017
nodename: ip-172-31-10-214
machine: x86_64
clock source: unix
detected number of CPU cores: 1
current working directory: /home/ubuntu/gericare
detected binary path: /home/ubuntu/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/ubuntu/gericare
your processes number limit is 3902
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...552 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x23680c0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 800448 bytes (781 KB) for 10 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x23680c0 pid: 1352 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1352)
spawned uWSGI worker 1 (pid: 1355, cores: 1)
spawned uWSGI worker 2 (pid: 1356, cores: 1)
spawned uWSGI worker 3 (pid: 1357, cores: 1)
spawned uWSGI worker 4 (pid: 1358, cores: 1)
spawned uWSGI worker 5 (pid: 1359, cores: 1)
spawned uWSGI worker 6 (pid: 1360, cores: 1)
spawned uWSGI worker 7 (pid: 1361, cores: 1)
spawned uWSGI worker 8 (pid: 1362, cores: 1)
spawned uWSGI worker 9 (pid: 1363, cores: 1)
spawned uWSGI worker 10 (pid: 1364, cores: 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "./gericare_site/urls.py", line 28, in <module>
    ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
NameError: name 'settings' is not defined
[pid: 1358|app: 0|req: 1/1] 129.22.21.193 () {44 vars in 785 bytes} [Sun Apr 23 18:25:16 2017] GET / => generated 81147 bytes in 85 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
